# Numpy Basics <hr style = "border:3px solid #DFC5FE"></hr>

Data Analyst: Christian C. Ortega <br>
Department: Electrical Engineering

In [7]:
#%pip install numpy --upgrade

In [8]:
#%pip install scipy

In [9]:
#%pip install scipy --upgrade

In [51]:
# import and packages
import numpy as np
from scipy import stats

# 1D Array

In [11]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [12]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
    ])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.shape(my_array)

(2, 3)

In [14]:
# transpose of a matrix
my_array = my_array.T

In [15]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
# add by row
np.sum(my_array,axis=0)

array([ 6, 15])

In [17]:
# add by column
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [18]:
# import and packages
import numpy as np
from scipy import stats

In [19]:
fruits = np.array([120, 60 ,85 ,150 ,200])
fruits

array([120,  60,  85, 150, 200])

In [20]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [21]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [56]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

In [54]:
# sample standard deviation
np.std(fruits, ddof=1)

np.float64(54.954526656136345)

In [24]:
np.median(fruits)

np.float64(120.0)

In [25]:
stats.mode(fruits)

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar Vs Panther

# Jaguar

In [26]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [27]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [28]:
jaguar_median = np.mean(jaguar)
jaguar_median

np.float64(9.399999999999999)

In [29]:
# sort
jaguar_sort = np.mean(jaguar)
jaguar_sort

np.float64(9.399999999999999)

In [30]:
# mode
stats.mode (jaguar)

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [31]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

np.float64(8.0)

In [32]:
# Q1
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.4)

In [33]:
# Q2
q2_jag = np.percentile(jaguar, 50)
q2_jag

np.float64(9.8)

In [34]:
# Q3
q3_jag = np.percentile(jaguar, 75)
q3_jag

np.float64(10.45)

In [35]:
# IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [36]:
# Sample variance
std_jag = np.var(jaguar, ddof=1)
std_jag

np.float64(4.86)

In [37]:
# Sample standard deviation
std_jag = np.std(jaguar, ddof=1)
std_jag

np.float64(2.2045407685048604)

# Panther

In [38]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [39]:
panther_mean = np.mean (panther)
panther_mean

np.float64(10.75)

In [40]:
# median
panther_median = np.mean (panther)
panther_median

np.float64(10.75)

In [41]:
# sort
panther_sort = np.mean (panther)
panther_sort

np.float64(10.75)

In [42]:
# mode
panther_mode = np.mean (panther)
panther_mode

np.float64(10.75)

In [43]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan

np.float64(10.9)

In [44]:
# Q1
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.125)

In [45]:
# Q2
q2_pan = np.percentile(panther, 50)
q2_pan

np.float64(9.55)

In [46]:
# Q3
q3_pan = np.percentile(panther, 75)
q3_pan

np.float64(10.625)

In [47]:
# IQR
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.5)

In [48]:
# Sample variance
std_pan = np.var(panther, ddof=1)
std_pan

np.float64(11.082777777777777)

In [49]:
# Sample standard deviation
std_pan = np.std(panther, ddof=1)
std_pan

np.float64(3.3290806204983645)